# Generated by Django 3.2 on 2023-03-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedb',
            name='creat_at',
            field=models.DateField(auto_now=True),
        ),
    ]
