# Generated by Django 3.2 on 2023-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_translatedb_creat_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='languges',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='languges',
            name='languge',
            field=models.CharField(max_length=40),
        ),
    ]
